### ISSUE TITLE
Precison and Recall Misplaced

### ISSUE THREAD

**Issue by HaishuoFang** [onehaitao/Att-BLSTM-relation-extraction#4]
If rows of confusion matrix are prediction and columns are labels, it seems they are misplaced.

https://github.com/onehaitao/Att-BLSTM-relation-extraction/blob/90db24659ec92442c0693cd086af8ce34691dc50/evaluate.py#L31

**Comment by onehaitao** [comment]
I printed the precision and recall of all relations, and the result is same as the official script.

**Comment by HaishuoFang** [comment]
Does the row mean predicted labels or true labels? I think it's a bit weird

**Comment by onehaitao** [comment]
I review my code and I think that row means the predicted labels, maybe the Perl script is wrong, but it does not affect the final F1.
