### ISSUE TITLE
I run the code and get the F1 score 82.73 

### ISSUE THREAD

**Issue by songhanyu** [onehaitao/Att-BLSTM-relation-extraction#5]
Hi, thanks for your code!I have a question,can you give me some advice? I run your code,but only get F1 score 82.73,never get 83.13 in your log file.If you have time, thanks for your advice.

**Comment by onehaitao** [comment]
You can check your version of Pytorch and CUDA. As far as I know, different versions lead to different results.

**Comment by songhanyu** [comment]
Thank you very much! I use Pytorch of v1.5.0, because I cannot get your 1.3.0 Pytorch(you write on the README page) on the official site https://pytorch.org/get-started/previous-versions/ .Can you tell me your version of Pytorch and CUDA, thanks again!!And it's so kind of you!

**Comment by onehaitao** [comment]
You can run the following commands:
`pip install torch==1.3.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html
`

**Comment by songhanyu** [comment]
Thanks very much!&nbsp;



---Original---
From: "HT ***@***.***&gt;
Date: Fri, May 7, 2021 21:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [onehaitao/Att-BLSTM-relation-extraction] I run the code and get the F1 score 82.73  (#5)




 
You can run the following commands:
 pip install torch==1.3.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html
