### ISSUE TITLE
semeval_scorer()计算分数问题

### ISSUE THREAD

**Issue by z1ouhan** [onehaitao/Att-BLSTM-relation-extraction#6]
您好，我看代码中的该函数计算分数似乎不关注标签的(e1,e2)的位置，这一点有一些疑惑。

**Comment by onehaitao** [comment]
`xDIRx` in `semeval_scorer()` is used to record examples where the label prediction is correct but the direction prediction is wrong, and you can see the detailed records in [`result.txt`](https://github.com/onehaitao/Att-BLSTM-relation-extraction/blob/master/result.txt).

**Comment by onehaitao** [comment]
`semeval_scorer()`函数中的`xDIRx`变量是用来记录那些标签预测正确但方向预测错误的例子数量的，你可以查看[`result.txt`](https://github.com/onehaitao/Att-BLSTM-relation-extraction/blob/master/result.txt)，这是官方评价脚本生成的结果，里面有详细的计算过程。我的`semeval_scorer()`函数是根据perl脚本内容改写的。
