### ISSUE TITLE
how to deal with the problem aboutAttributeError: 'SemEvalDataLoader' object has no attribute '__collate_fn'

### ISSUE THREAD

**Issue by Nuyoahwh** [onehaitao/Att-BLSTM-relation-extraction#7]
AttributeError: 'SemEvalDataLoader' object has no attribute '__collate_fn'
I want to know how to deal with it ,where is the '__collate_fn'

**Comment by onehaitao** [comment]
hi,  I think it has something wrong related with the version of some packages, it is recommended to use Python 3.6 and Python 1.3.0 to try again.  Or you can try to convert all private variables (such as **___collate_fn_**) into the public variables (such as **_collate_fn_**), refered in this [Issue](https://github.com/onehaitao/Att-BLSTM-relation-extraction/issues/1).
